apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u3f6mu1ir-go
  janus-idp.io/tekton: u3f6mu1ir-go
  backstage.io/kubernetes-id: u3f6mu1ir-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u3f6mu1ir-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
